piVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: stock-trading
spec:
  selector:
    app.kubernetes.io/name: account-service
  ports:
    - name: http
      port: 80
      targetPort: 8080