piVersion: apps/v1
kind: Deployment
metadata:
  name: data-feed-service
  namespace: stock-trading
  labels:
    app.kubernetes.io/name: data-feed-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: data-feed-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: data-feed-service
      annotations:
        scs.gate/sbom-digest: ""
        scs.gate/critical-count: "0"
    spec:
      containers:
        - name: data-feed-service
          image: ghcr.io/sinhnguyen1411/stock-trading/data-feed-service
          ports:
            - containerPort: 8080