apiVersion: v1
kind: Service
metadata:
  name: market-data-service
  namespace: stock-trading
  labels:
    app.kubernetes.io/name: market-data-service
spec:
  selector:
    app.kubernetes.io/name: market-data-service
  ports:
    - port: 80
      targetPort: 8080
