apiVersion: v1
kind: Service
metadata:
  name: qwen-llm-service
  namespace: stock-trading
  labels:
    app: qwen-llm-service
spec:
  type: ClusterIP
  ports:
    - port: 11434
      targetPort: 11434
      protocol: TCP
      name: http-ollama
  selector:
    app: qwen-llm-service
